name: kokugo_kore
description: "国語コレ！- ひらがなから読解・作文まで"
publish_to: 'none'

version: 1.4.0+9

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  shared_core:
    path: H:/マイドライブ/apps/shared_core
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.3.0
  intl: ^0.19.0
  confetti: ^0.8.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_database: ^11.3.10
  in_app_purchase: ^3.2.0
  google_fonts: ^6.2.1
  flutter_tts: ^4.0.2
  uuid: ^4.0.0
  google_mobile_ads: ^5.2.0
  gal: ^2.2.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  fl_chart: ^0.67.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  freezed: ^2.4.6
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/app_icon_512.jpg"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logos/app_icon_512.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/legal/
    - assets/characters/
    - assets/character_levels/
    - assets/characters_lvmax/
    - assets/logos/
    - assets/images/
    - assets/backgrounds/
